token: ''
nickname: ''
settings: {
  repositories: {
    type: 'owner'
    sort: 'full_name'
    direction: 'asc'
    visibility: 'public'
    affiliation: 'owner,collaborator,organization_member'
  }
}
filter: {
  repositories: [][]
}
sort: {
  repositories: []
}
