// This file is auto-generated by graphql-codegen.
export const operations = {
  "c268856180c7e7aa268a3907185cf45fae921abe839164a28db90fd797bdf9c9": "query Viewer {\n  viewer {\n    login\n  }\n}\n"
} as const;
