name: E2E Tests

on:
  deployment_status:

jobs:
  test:
    if: github.event.deployment_status.state == 'success' && contains(github.event.deployment.environment, 'Preview')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          BASE_URL: ${{ github.event.deployment_status.target_url }}
        run: npx playwright test
